name: 'PagerDuty'
description: 'Notify PagerDuty based on result of Github Actions'
author: 'Meetup'
inputs: 
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'