# todo: create docker publish workflow
# https://github.com/actions/docker
name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test
      # https://github.com/actions/action-builder/tree/master/docker
      - uses: actions/action-builder/docker@master